use_frameworks!
platform :ios, '10.0'
swift_version = '3.0'

target 'DomesticaSender' do
pod 'Domestica', :path => '../../'
end

target 'DomesticaReceiver' do
pod 'Domestica', :path => '../../'
end

post_install do |installer|
 installer.pods_project.targets.each do |target|
   target.build_configurations.each do |config|
     config.build_settings['SWIFT_VERSION'] = '3.0'
   end
 end
end
